INSERT INTO Teacher values (201,'COMPUTER SCIENCE','DHIRAJ');
INSERT INTO Teacher values (202,'DESIGN AND ANALYSIS OF ALGORITHM','MANOJ');
INSERT INTO Teacher values (203,'ELECTRONICS','SHIVA');
INSERT INTO Teacher values (204,'DATA STRUCTURES','AAYUSH');
INSERT INTO Teacher values (205,'C PROGRAMMING','KAVI');
