
INSERT INTO STUDENT values (101,'COMPUTER SCIENCE','RAVI');
INSERT INTO STUDENT values (102,'INFORMATION TECHNOLOGY','ASHISH');
INSERT INTO STUDENT values (103,'ELECTRONICS AND COMMUNICATION','AKASH');
INSERT INTO STUDENT values (104,'COMPUTER SCIENCE','AAYUSH');
INSERT INTO STUDENT values (105,'INFORMATION TECHNOLOGY','ISHAN');
